networks:
  express:
    driver: bridge

services:
  postgres:
    image: "postgres:17-alpine"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drizzle
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - express
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

  drizzle:
    image: node
    container_name: express
    volumes:
      - ./:/app
    command: bash -c "cd /app && npm run server-docker"
    ports:
      - "3000:3000"
    networks:
      - express
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: